### ISSUE TITLE
Prototype Polution

### ISSUE THREAD

**Issue by genus1** [judahtanthony/node-aescrypt#10]
* **I'm submitting a ...**
[ ] minor bug report

* **Summary**
I just installed the node-aescrypt  and received the below error.  I installed the latest version of meow an yargs-parser but no effect.

  Low             Prototype Pollution
  Package         yargs-parser
  Patched in      >=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2
  Dependency of   node-aescrypt
  Path            node-aescrypt > meow > yargs-parser
  More info       https://npmjs.com/advisories/1500

**Comment by judahtanthony** [comment]
Thanks @genus1 .  This was due to some old dependencies.  I believe I have upgraded all that I could, so you should be able to pull down the latest.
