### ISSUE TITLE
Can't resolve 'fs'

### ISSUE THREAD

**Issue by ogadepoju** [judahtanthony/node-aescrypt#24]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Hi, i'm trying to implement node-aescrypt to encrypt and decrypt files, which works well from the command line, but when trying to import the module into my ionic angular project, i keep getting this error:
Error: Module not found: Error: Can't resolve 'fs' in 'C:\Users\USER\Downloads\foyeGab\node_modules\node-aescrypt\build\module\lib'
 Error: Module not found: Error: Can't resolve 'fs' in 'C:\Users\USER\Downloads\foyeGab\src\app\home'

 Error: Module not found: Error: Can't resolve 'crypto' in 'C:\Users\USER\Downloads\foyeGab\node_modules\node-aescrypt\build\module\lib'
[ng] BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
[ng] This is no longer the case. Verify if you need this module and configure a polyfill for it.
[ng] If you want to include a polyfill, you need to:
[ng]    - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
[ng]    - install 'crypto-browserify'
[ng] If you don't want to include a polyfill, you can use an empty module like this:
[ng]    resolve.fallback: { "crypto": false }

Error: Module not found: Error: Can't resolve 'stream' in 'C:\Users\USER\Downloads\foyeGab\node_modules\node-aescrypt\build\module\lib'
[ng] BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
[ng] This is no longer the case. Verify if you need this module and configure a polyfill for it.
[ng] If you want to include a polyfill, you need to:
[ng]    - add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
[ng]    - install 'stream-browserify'
[ng] If you don't want to include a polyfill, you can use an empty module like this:
[ng]    resolve.fallback: { "stream": false }

Kindly Help fix this as i can't get to wrap my head as to the cause of this issue
* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by judahtanthony** [comment]
Ah.  That makes sense.  This is a Node.js library, not a browser library.  It has utilities for reading files off the filesystem which we couldn't do in the browser (unless we did some really cool ByteArray drag-n-drop stuff).  You can attempt to use Node.js polyfills, but I don't know if that is going to be worthwhile.

**Comment by ogadepoju** [comment]
Thanks for your response.
But i'm trying to decrypt an ebook within the app and it doesn't use browser as the encrypted file is already downloaded locally into the device data directory, which is suppose to decrypt it locally. Can you advice as to what to do to resolve this issue

Thanks

**Comment by ogadepoju** [comment]
The major issue now is: 
Error: Module not found: Error: Can't resolve 'fs' in 'C:\Users\USER\Downloads\foyeGab\node_modules\node-aescrypt\build\module\lib'
Error: Module not found: Error: Can't resolve 'fs' in 'C:\Users\USER\Downloads\foyeGab\src\app\home'

**Comment by ogadepoju** [comment]
Point gotten
thank you
