### ISSUE TITLE
Thank you for making this!

### ISSUE THREAD

**Issue by XLpacman805** [judahtanthony/node-aescrypt#6]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[X] question about how to use this project

* **Summary**
Thank you for making this you're a life saver! Especially that encrypt buffer function. I had to read through the source code to find it but it's still helpful none the less! 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by judahtanthony** [comment]
Thanks!  I'm happy to hear it is useful to someone.
